# Generated by Django 2.0.7 on 2018-08-27 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.CharField(max_length=535)),
                ('skill_level', models.IntegerField(default=0)),
                ('months_worked', models.IntegerField(default=0)),
                ('last_project', models.CharField(max_length=535)),
                ('website', models.URLField()),
                ('documentation', models.URLField()),
                ('github', models.URLField()),
                ('why', models.CharField(max_length=535)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=535)),
                ('title1', models.CharField(max_length=535)),
                ('points1', models.IntegerField(default=0)),
                ('title2', models.CharField(max_length=535)),
                ('points2', models.IntegerField(default=0)),
                ('title3', models.CharField(max_length=535)),
                ('points3', models.IntegerField(default=0)),
                ('title4', models.CharField(max_length=535)),
                ('points4', models.IntegerField(default=0)),
                ('title5', models.CharField(max_length=535)),
                ('points5', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SkillChart'),
        ),
    ]
