# Generated by Django 2.0.7 on 2018-08-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
