# Generated by Django 2.0.7 on 2018-08-27 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('place', models.CharField(max_length=255)),
                ('place_logo', models.CharField(max_length=255)),
                ('course_title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('main_focus', models.CharField(max_length=255)),
                ('achievements', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
