# Generated by Django 2.0.7 on 2018-08-27 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('person', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('testimony', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=255)),
                ('linkedin', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
