# Generated by Django 2.0.7 on 2018-08-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180830_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenuitem',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
