# Generated by Django 2.1 on 2018-08-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180831_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
