# Generated by Django 2.0.7 on 2018-09-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_skillcategory_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillcategory',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
