# Generated by Django 2.0.7 on 2018-09-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180904_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillcategory',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
