# Generated by Django 2.1 on 2018-10-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_skillcategory_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='achievements',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='responsibilities',
        ),
    ]
