# Generated by Django 2.1 on 2018-10-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20181009_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='main_focus',
            field=models.TextField(),
        ),
    ]
