# Generated by Django 2.1 on 2018-10-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20181009_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='cta',
            field=models.CharField(default='View More', max_length=255),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
