# Generated by Django 2.1 on 2018-10-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_casestudy_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='summary',
            field=models.CharField(max_length=535),
        ),
    ]
