# Generated by Django 2.1 on 2018-10-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20181009_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
