# Generated by Django 2.1 on 2018-10-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20181009_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='preferred',
            field=models.BooleanField(default=False),
        ),
    ]
