# Generated by Django 2.1 on 2018-10-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20181012_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='coming_soon',
            field=models.BooleanField(default=False),
        ),
    ]
